services:
  # Backend Service
  - type: web
    name: sihps25152-backend
    runtime: node
    region: singapore
    plan: free
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /api/auth/login
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: VITE_MAPBOX_TOKEN
        sync: false
      - key: FRONTEND_URL
        sync: false

  # Frontend Service
  - type: web
    name: sihps25152-frontend
    runtime: node
    region: singapore
    plan: free
    rootDir: client
    buildCommand: npm install && npm run build
    startCommand: npm run preview
    envVars:
      - key: VITE_MAPBOX_TOKEN
        sync: false
      - key: VITE_API_URL
        sync: false
